### ISSUE TITLE
Open With for Thunderbird 78 

### ISSUE THREAD

**Issue by stardepp** [darktrojan/openwith#281] opened 2020-09-10 07:03 UTC
Will there be an update for Thunderbird 78 and if so, when? How can I donate for Open With?

**Comment by robcast** [comment] 2020-09-14 16:28
I am also on Thunderbird 78 and I miss OpenWith ;-(

The first problem is that there seems to be no way to open the preferences dialog. Is this something that could be easily fixed in the code?

**Comment by darktrojan** [comment] 2020-09-14 22:16
The current version does not work on Thunderbird 78. At all.

However, the version for Firefox should at least partially work. Be warned it's quite different by necessity.

I haven't had time for working on this lately.

**Comment by robcast** [comment] 2020-09-17 16:52
The first time I tried to install the Firefox plugin (6.9.2) in Thunderbird a while back I could install it but it would not show the "Preferences..." menu option in the plugin list.

Today I tried again with TB 78.2.2 and OpenWith 7.2.2 and it does install and I can get to the preferences! :-)

But when I click "Test installation" in the preference dialog I only get an error in the log:
```
ExtensionError: No such native application open_with ExtensionUtils.jsm:56:5
    ExtensionError resource://gre/modules/ExtensionUtils.jsm:56
    startupPromise resource://gre/modules/NativeMessaging.jsm:83
```
​
I have a working installation of OpenWith in Firefox but it does not work in Thunderbird. I also re-downloaded and re-ran `open_with_mac.py install` which did not help.

Anything else I could try?

P.S. and thanks again for OpenWith!

**Comment by robcast** [comment] 2020-09-17 18:02
After stumbling over https://github.com/kkapsner/keepassxc-mail/issues/5 I changed the directory for NativeMessagingHosts in `open_with_mac.py`: https://github.com/robcast/openwith/commit/8d27fc4d94052358b6fcfbe20af533987f327704

Now the plugin recognises the helper script but I get errors when I click "look for browsers":
```
Unchecked lastError value: Error: browsers is undefined
    find_new_browsers moz-extension://2426bdf7-ef53-bc42-b9de-c44e2ecda9a5/options.js:671
```
needs more debugging...

**Comment by KoborOld** [comment] 2020-09-21 19:05
Would be happy for an update to V78, thank you!

**Comment by superbonaci** [comment] 2020-09-25 20:02
Also requesting for an update for TB78. Ask for donations if you need to!

**Comment by stardepp** [comment] 2020-09-26 04:22
Hello darktrojan. I am also very willing to donate to you. Maybe it will give you strength to develop the addon Open With for Thunderbird further than WebExtension for Thunderbird 78 and upwards.

**Comment by C-Denninger** [comment] 2020-11-05 15:50
Hello,

@robcast's comment triggered me to try and add [Open With for Firefox](https://addons.mozilla.org/nl/firefox/addon/open-with/) in Thunderbird. This _kind of works_ at least on my (Dutch) Windows 10, I'm not a Mac user.
The problem is; I don't know how to fix the right-click-menus in the e-mails themselves, so the add-on is running but I cannot use Open With properly...

### Thus far I did the following:
_Because I use the Dutch versions of Thunderbird and Windows, I tried to translate the menu-names to English, I don't know if they are all correct, so I added some Dutch names to._

1. Download the [Firefox v7.2.2 add-on](https://addons.mozilla.org/nl/firefox/addon/open-with/) to your PC.
2. Open the add-on manager (Dutch: Add-onbeheerder) in Thunderbird and import the downloaded add-on using the chainring-icon (Dutch: tandwiel-icoon) in the right-hand top corner of the Extensions-tab.
3. Restart Thunderbird if necessary.
4. Open the Open With options from the add-on manager; klick the three dots next to the add-on here. ![afbeelding](https://user-images.githubusercontent.com/55947148/98256803-4989b000-1f7f-11eb-8302-b53ea13faa46.png)
5. Now you can add your browsers like in Firefox and you can donate here to. You might need to install Python first. 
![afbeelding](https://user-images.githubusercontent.com/55947148/98257199-b00ece00-1f7f-11eb-95ba-51d8af1ca7d2.png)
6. You can add the Open With-icon to Thunderbirds toolbar (Dutch: Werkbalk) to. 
![afbeelding](https://user-images.githubusercontent.com/55947148/98258023-a6399a80-1f80-11eb-8ca3-14bef5ed06d8.png)
### The final problem apart from a new Open With for Thunderbird version...
7. **And then it stops…** I cannot figure out how to add Open With to the right-klick-menu on links in the e-mails. In Firefox this works fine but in Thunderbird this sub-menu does not appear. Maybe someone here has a clue? 
![afbeelding](https://user-images.githubusercontent.com/55947148/98262437-e64f4c00-1f85-11eb-965b-184787b318c8.png)

**Comment by sonofeft** [comment] 2020-11-08 17:47
Open With is a great add-on that I used every day prior to the 78.4 update... I hope you can find the time to update it.
Thanks

**Closed** 2020-11-08 17:49 UTC

**Comment by superbonaci** [comment] 2020-11-08 18:01
Why closed? Been fixed?

**Comment by KoborOld** [comment] 2020-11-08 18:32
No idea, I got an instant Closed on a different Ticket for MPC-BE, is this a tendency nowadays?

**Comment by scalisi** [comment] 2020-11-09 00:39
> Why closed? Been fixed?

I assume @stardepp no longer wanted to be notified about this issue, which was opened by them. And rather than unsubscribe, they closed the issue.

@darktrojan, please consider reopening this issue. Thank you.

**Comment by LinuxOpa** [comment] 2020-11-11 11:50
Please make OpenWith work for the current Thunderbird version (78.4.2+).  This is a very good AddOn for which I would also like to spend a few dollars - if it works. **Thank you very much!**

**Comment by C-Denninger** [comment] 2020-12-19 10:19
Hello, just in case you missed it in case #276 the issue is solved. I quote @Robcast:
> Please check out the new VERSION_7.2.3. Now it works in Thunderbird 78+ (tested on TB 78.5.1 on macOS).
> 
> Hooray and lots of thanks for @darktrojan !!!

And my own reply from there:
> Yesss!
> Tested on Windows 10 with Thunderbird version 78.5.1 (64 bits) and working!
> 
> Note; at the moment of writing version 7.2.3 is seen as an **old version**, it can be found at the [Thunderbird Open-With add-on **versions** page](https://addons.thunderbird.net/thunderbird/addon/open-with/versions/).
> 
> Thanks indeed!

**Comment by DoctorSubtilis** [comment] 2021-04-03 13:35
No: in my linux thunderbird 78.7 doesn't work at all!
Where should I put the folder "native-messaging-hosts"? Wherever I put it, it doesn't work.
